const UserManageList = [
  {
    email: "user1@tng.com",
    password: " ",
    name: "Trần Minh Hy",
    date: "2000-10-01",
    add: "01 Hoàng Hoa Thám, Đà Nẵng",
    phone: "0333456452",
    img: "https://img.freepik.com/premium-vector/young-smiling-man-adam-avatar-3d-vector-people-character-illustration-cartoon-minimal-style_365941-687.jpg?w=2000",
  },
  {
    email: "user2@tng.com",
    password: " ",
    password: " ",
    name: "",
    date: "",
    add: "",
    phone: "",
    img: "",
  },
  {
    email: "user3@tng.com",
    password: " ",
    password: " ",
    name: "",
    date: "",
    add: "",
    phone: "",
    img: "",
  },
  {
    email: "user4@tng.com",
    password: " ",
    password: " ",
    name: "",
    date: "",
    add: "",
    phone: "",
    img: "",
  },
  {
    email: "user5@tng.com",
    password: " ",
    password: " ",
    name: "",
    date: "",
    add: "",
    phone: "",
    img: "",
  },
  {
    email: "user6@tng.com",
    password: " ",
    password: " ",
    name: "",
    date: "",
    add: "",
    phone: "",
    img: "",
  },
  {
    email: "user7@tng.com",
    password: " ",
    password: " ",
    name: "",
    date: "",
    add: "",
    phone: "",
    img: "",
  },
  {
    email: "user8@tng.com",
    password: " ",
    password: " ",
    name: "",
    date: "",
    add: "",
    phone: "",
    img: "",
  },
  {
    email: "user9@tng.com",
    password: " ",
    password: " ",
    name: "",
    date: "",
    add: "",
    phone: "",
    img: "",
  },
  {
    email: "user10@tng.com",
    password: " ",
    password: " ",
    name: "",
    date: "",
    add: "",
    phone: "",
    img: "",
  },
  {
    email: "user11@tng.com",
    password: " ",
    password: " ",
    name: "",
    date: "",
    add: "",
    phone: "",
    img: "",
  },
  {
    email: "user12@tng.com",
    password: " ",
    password: " ",
    name: "",
    date: "",
    add: "",
    phone: "",
    img: "",
  },
];

const UserRecheck = localStorage.getItem("users");

if (!UserRecheck) {
  localStorage.setItem("users", JSON.stringify(UserManageList));
}
